### ISSUE TITLE
HTTP POST Method Typo

### ISSUE THREAD

**Issue by daveajstearns** [learn-co-curriculum/dsc-http-request-response-codealong#1]
`url = 'http://httpbin.org/post'
file_list = [
    ('image', ('fi.png', open('images/fi.png', 'rb'), 'image/png')),
    ('image', ('fi2.jpeg', open('images/fi2.jpeg', 'rb'), 'image/png'))
]
r = requests.post(url, files=file_list)
print(r.text)`

The second file tuple should have an ending of **'image/jpeg'**

**Comment by bpurdy-ds** [comment]
Fixed, and closed with commit: https://github.com/learn-co-curriculum/dsc-http-request-response-codealong/issues/1#issue-573579394h
