### ISSUE TITLE
SaturnCloud Timing Out when Requesting from Google

### ISSUE THREAD

**Issue by mark-barbour** [learn-co-curriculum/dsc-http-request-response-codealong#2]
Mark Barbour

## Link to Canvas

https://learning.flatironschool.com/courses/6221/assignments/226307?module_item_id=529098

## Issue Subtype

- [ ] Master branch code
- [ ] Solution branch code
- [ ] Code tests
- [ ] Layout/rendering issue
- [ ] Instructions unclear
- [ X] Other (explain below)

### Source

```
resp = requests.get('https://www.google.com')
```

### Concern

This code cell runs when cloned down locally, but timesout when run in SaturnCloud.

## (Optional) Proposed Solution

Unknown at this time

## What OS Are You Using?

- [ ] OS X
- [ ] Windows
- [ ] WSL
- [ ] Linux
- [X] Saturn Cloud from Canvas

**Comment by jessepisel** [comment]
Thanks for opening this @mark-barbour :wave:. Google was not on the approved URL list for Saturn Cloud. I have updated the lesson to point to an approved URL going forward. Notebooks are updated at this time.

**Comment by jessepisel** [comment]
fixed with [0192344](https://github.com/learn-co-curriculum/dsc-http-request-response-codealong/commit/0192344f5f3df72d19565e21e9bbd4baa41a07d2)
